import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "./globals.css";
import Nav1 from "@/frontend/components/navs/nav1";

const geistSans = Inter({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  display: "swap",
  weight: ["200","300","400", "700", "800", "900"],
});

const geistMono = Inter({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  display: "swap",
  weight: ["200","300","400", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav1 />
        {children}
      </body>
    </html>
  );
}
