name: Deploy to CapRover

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configurar Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t david12997/cominsur.co:latest .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push david12997/cominsur.co:latest

      # Step 5: Deploy to CapRover
      - name: Deploy to CapRover
        env:
          CAPROVER_SERVER: ${{ secrets.CAPROVER_SERVER }}
          CAPROVER_PASSWORD: ${{ secrets.CAPROVER_PASSWORD }}
        run: |
          npx caprover deploy \
            -h $CAPROVER_SERVER \
            -p $CAPROVER_PASSWORD \
            -a my-nextjs-app \
            -i david12997/cominsur.co:latest